# Testing mode
currently_testing: false


# Environment Configurations 
adb_path: "C:/platform-tools/adb.exe"
# match_threshold: 0.8
screenshot_path: "Screenshots/screen.png"
template_path: "Templates/"
device_ip: "127.0.0.1:5555"
use_gpu: true


# Fine-tunable static Values 




# TP Interaction Delays (in seconds)
curse_execution_buffer: 45
curse_conflict_threshold: 240


# Screen Coordinates for various Trading Post Operations at 1080p resolution
screen_coordinates:
  order_timer_scan_region: [450, 450, 1000, 600]
  tp_workers_entry_button: [485, 965]
  productivity_worker_1_region: [630, 485, 825, 525]
  productivity_worker_2_region: [630, 910, 825, 950]
  productivity_worker_3_region: [845, 485, 1040, 525]
  dorm1_info_region: [750, 280]
  dorm2_info_region: [750, 530] 
  dorm3_info_region: [750, 760]
  dorm4_info_region: [750, 1000]
  factory_workers_entry_button: [485, 965]